version: '3'
services:
  app:
    build:
      context: ./docker/construct_app      # Dockerfile保存場所
      dockerfile: Dockerfile-app    # Dockerfileファイル名
    image: nn-app-4                 # docker image name
    ports:                          # ポート接続
      - 3000:3000
    links: 
      - mongo
    depends_on: 
      - mongo
    volumes:                        # mount workdir
      - ./myapp:/src
    command: [sh, -c, npm install && npm run dev]

  mongo:
    image: mongo
    command: 
      - mongod
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

